name: lefly
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.1
  permission_handler: ^8.1.2
  expansion_card: ^0.1.0
  provider: ^5.0.0
  clippy_flutter: ^1.1.1
  cupertino_icons: ^1.0.3
  cloud_firestore: ^2.3.0
  firebase_core: ^1.3.0
  geolocation: ^1.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  
  uses-material-design: true

  assets:
   - images/

 